[package]
name = "semantic-analyzer-rs"
version = "0.1.0"
authors = ["Evgeny Ukhanov <mrlsd@ya.ru>"]
description = " Semantic analyzer library for compilers written in Rust for semantic analysis of programming languages, with code generation for any backend."
license = "MIT"
edition = "2021"

[lib]
doctest = false

[dependencies]
nom_locate = "4.1"
nom = "7.1.3"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master" }
thiserror = "1.0"

[features]
default = ["inkwell/llvm15-0"]
llvm12 = ["inkwell/llvm12-0"]
